[util] Develop linkedList module
InfraSail/wkv pull request #5
Opened 2022-03-08 11:25 UTC by million-2002

### Purpose

- 完善了sds.go模块，新增linkedlist，skiplist，没有测试，可能全是错的

### Changes

- sds.go linkedlist.go skiplist.go test_sds.go

### Review Instructions

- No instructions.

2022-03-08 11:37 UTC, Sigma711 requested changes
I think you should use go-fmt to specify your code format.

2022-03-08 11:46 UTC, Sigma711 requested changes
And you should modify it.

2022-03-08 11:46 UTC, Sigma711 commented on go.mod
> +module module1
```suggestion
module wkv
```

2022-03-08 12:57 UTC, Sigma711 commented on go.mod
> +module module1
LGTM

2022-03-08 12:59 UTC, Sigma711 requested changes
Change [wkv](https://github.com/InfraSail/wkv)/[.github](https://github.com/InfraSail/wkv/tree/main/.github)/[workflows](https://github.com/InfraSail/wkv/tree/main/.github/workflows)/go.yml to:
```yaml
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
```

2022-03-08 13:07 UTC, million-2002 commented
ok

2022-03-09 02:18 UTC, Sigma711 requested changes
git mv test/util/sds_test.go pkg/util/

2022-03-09 02:20 UTC, Sigma711 commented on pkg/util/skiplist.go
> +	node.SetLevel(level)
`// TODO: node.SetLevel(level)`

2022-03-09 02:32 UTC, Sigma711 requested changes
1. Improve the code according to my requirement in one commit.
2. Fix all warnings checked by GolangCI-Lint in the next commit.
3. Finally, fix all logic bug in it in order to make it pass all unit tests and make it sense in last commit of this time.

2022-03-09 02:32 UTC, Sigma711 commented on pkg/util/sds.go
> +	if ask_split[0] == "set" && ask_split[0] == "SET" {
I think you should change it to this style:
```go
if x := ask_split[0]; x == "set" && x == "SET" {
```
In addition, you should reconsider the operator `&&`. Does it make sense?

2022-03-09 02:32 UTC, Sigma711 commented on pkg/util/sds.go
> +	} else if ask_split[0] == "get" && ask_split[0] == "GET" {
I think you should change it to this style:
```go
} else if x := ask_split[0]; x == "get" && x == "GET" {
```
In addition, you should reconsider the operator `&&`. Does it make sense?

2022-03-09 02:32 UTC, Sigma711 commented on pkg/util/skiplist.go
> +	node.SetLevel(level)
You should change that to it:
```go
// TODO: node.SetLevel(level)
```

2022-03-09 02:45 UTC, Sigma711 requested changes
Undo the code comments in Line 22 - Line 26 of [.github/workflows/go.yml](https://github.com/InfraSail/wkv/pull/5/files#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9f).

2022-03-13 15:00 UTC, Sigma711 requested changes
bullshit

2022-03-15 13:01 UTC, Sigma711 requested changes
This directory .vscode should be put into `.gitignore` file.

2022-03-15 13:02 UTC, million-2002 commented
> This directory .vscode should be put into `.gitignore` file.

ok

2022-03-15 13:03 UTC, Sigma711 requested changes
And why delete `sds` module?

2022-03-15 13:04 UTC, million-2002 commented
> And why delete `sds` module?

sth wrong in the file

2022-03-15 13:06 UTC, Sigma711 commented
> > This directory .vscode should be put into `.gitignore` file.
> 
> ok

Modify it. I think `sds` module should not be absent.

2022-03-15 13:08 UTC, Sigma711 commented
> > And why delete `sds` module?
> 
> sth wrong in the file

Modify it. I think `sds` module should not be absent.

2022-03-15 15:01 UTC, Sigma711 requested changes
Fix it.

2022-03-15 15:01 UTC, Sigma711 commented on pkg/util/skiplist.go
> +	//TODO:node.SetLevel(level)
1 space after `//`
1 space after `:`

2022-03-15 15:13 UTC, Sigma711 requested changes
Fix it.

2022-03-15 15:13 UTC, Sigma711 commented on pkg/util/sds.go
> +		s.len ++
no space before `++`

2022-03-15 15:41 UTC, Sigma711 requested changes
Fix it.

2022-03-15 15:41 UTC, Sigma711 commented on .gitignore
> +.vscode
Line 7 should be deleted.

2022-03-17 10:59 UTC, million-2002 reviewed
ok

2022-05-05 09:22 UTC, closed without merging